version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: metin2cms:latest
    container_name: metin2cms_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
    networks:
      - metin2cms
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - redis

  # MySQL removed - CMS connects to external game server database

  redis:
    image: redis:7-alpine
    container_name: metin2cms_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass redis_password
    networks:
      - metin2cms

  nginx:
    image: nginx:alpine
    container_name: metin2cms_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - metin2cms

  # PhpMyAdmin removed - not needed for external database connection

volumes:
  redis_data:
    driver: local

networks:
  metin2cms:
    driver: bridge